#!/usr/bin/env bash
# scripts/gen-skills-manifest.sh — regenerate config/skills-version.json's
# per-recipe pin data (version, aggregate checksum, fileCount) + aggregate
# bundle checksum FROM a skills dir's own index.json. Preserves the
# source-provenance fields (source, sourceBranch, sourceCommit, sourceSha,
# sourceRelease, bundleMethod, updateCommand) that are set when the subtree
# is (re)pulled — this script only refreshes the recipe rollup so the manifest
# never drifts from the bundle it describes.
#
# Runtime-free repo: bash + python3 only (python3 is already a hard worker
# dependency). NO node, NO npm.
#
# Usage:
#   scripts/gen-skills-manifest.sh [--skills-dir DIR] [--manifest FILE] [--bundled-at ISO8601]
# Defaults: --skills-dir <repo>/skills  --manifest <repo>/config/skills-version.json
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SELF_DIR/.." && pwd)"

SKILLS_DIR="$REPO_DIR/skills"
MANIFEST="$REPO_DIR/config/skills-version.json"
BUNDLED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

while (( $# )); do
  case "$1" in
    --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
    --manifest) MANIFEST="$2"; shift 2 ;;
    --bundled-at) BUNDLED_AT="$2"; shift 2 ;;
    *) echo "gen-skills-manifest.sh: unknown flag $1" >&2; exit 2 ;;
  esac
done

INDEX="$SKILLS_DIR/index.json"
[[ -r "$INDEX" ]] || { echo "gen-skills-manifest.sh: no index.json at $INDEX" >&2; exit 1; }

python3 - "$INDEX" "$MANIFEST" "$BUNDLED_AT" <<'PY'
import json, sys, hashlib, os

index_path, manifest_path, bundled_at = sys.argv[1], sys.argv[2], sys.argv[3]

idx = json.load(open(index_path))
recipes_in = idx.get("recipes", {})

# Per-recipe rollup: version + aggregate recipe checksum (the skill-checksum.mjs
# body hash the pack already computed, carried in index.json) + fileCount.
recipes_out = {}
for name in sorted(recipes_in):
    r = recipes_in[name]
    files = r.get("files", [])
    recipes_out[name] = {
        "version": r.get("version"),
        "checksum": r.get("checksum"),
        "fileCount": len(files),
    }

# Aggregate bundle checksum: deterministic sha256 over the sorted
# "<recipe>=<checksum>" lines, so a single field flips if ANY recipe's pinned
# checksum changes. Independent of the pack's own aggregate (which we don't
# have here) — purely derived from index.json, reproducible by anyone.
agg_src = "\n".join(f"{n}={recipes_out[n]['checksum']}" for n in sorted(recipes_out))
aggregate = "sha256:" + hashlib.sha256(agg_src.encode("utf-8")).hexdigest()

# Preserve provenance fields from the existing manifest if present.
existing = {}
if os.path.exists(manifest_path):
    try:
        existing = json.load(open(manifest_path))
    except Exception:
        existing = {}

out = {
    "_comment": "Pinned skills bundle manifest. cfw-render vendors its recipe closure in-repo (skills/), source-synced from the private source repo (ecosystem/harness/skills) via scripts/sync-skills.sh — git-subtree + the public cfw-social/cfw-skills repo are RETIRED (2026-09-01). Source-provenance fields are set by sync-skills.sh; the recipes rollup + aggregateChecksum are regenerated by scripts/gen-skills-manifest.sh from the bundle's own skills/index.json. The worker reads this at startup to log/assert its skills version; scripts/verify-skills-bundle.sh checksum-verifies on-disk recipe files against skills/index.json's per-file hashes.",
    "source": existing.get("source", "ecosystem/harness/skills"),
    "sourceCommit": existing.get("sourceCommit"),
    "sourceRelease": idx.get("release", existing.get("sourceRelease")),
    "sourceSha": idx.get("sourceSha", existing.get("sourceSha")),
    "recipeCount": len(recipes_out),
    "aggregateChecksum": aggregate,
    "bundledAt": bundled_at,
    "bundleMethod": existing.get("bundleMethod", "scripts/sync-skills.sh (direct copy from private source repo; git-subtree retired)"),
    "updateCommand": existing.get("updateCommand", "CFW_SKILLS_SRC=<path-to-private-skills-repo> scripts/sync-skills.sh"),
    "recipes": recipes_out,
}

with open(manifest_path, "w") as f:
    json.dump(out, f, indent=2)
    f.write("\n")

print(f"gen-skills-manifest.sh: wrote {manifest_path} — {len(recipes_out)} recipes, aggregate {aggregate[:23]}...")
PY
